#!/usr/bin/env bash
# manual-install.sh — self-contained (no repo clone required).
# Generated by tools/gen-manual.sh from the mac-setup dotfiles.
#
#   INSTALL_PORTS=0 bash manual-install.sh   # only write config files
#   bash manual-install.sh                   # write configs + install ports
set -euo pipefail

INSTALL_PORTS="${INSTALL_PORTS:-1}"
say() { printf '==> %s\n' "$*"; }

write_file() {
  local dest="$1"
  mkdir -p "$(dirname "$dest")"
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    cp "$dest" "$dest.bak.$(date +%s)"
  fi
  cat > "$dest"
}

if [ "$INSTALL_PORTS" = "1" ]; then
  if ! xcode-select -p >/dev/null 2>&1; then
    say "Installing Xcode Command Line Tools (finish the dialog, then re-run)..."
    xcode-select --install || true
  fi
  if [ ! -x /opt/local/bin/port ]; then
    echo "MacPorts is not installed. Install the macOS 26 .pkg from"
    echo "https://www.macports.org/install.php and re-run this script."
    exit 1
  fi
  export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
  say "Updating MacPorts (sudo port selfupdate)..."
  sudo port selfupdate
  say "Installing ports..."
  sudo port install neovim ripgrep fd fzf lazygit tree-sitter-cli \
    nodejs22 python312 go tmux starship git kitty
  sudo port select --set python3 python312 || true
  sudo port select --set nodejs  nodejs22  || true
  if command -v infocmp >/dev/null 2>&1 && ! infocmp tmux-256color >/dev/null 2>&1; then
    say "Adding tmux-256color terminfo (fallback)..."
    curl -fsSL https://raw.githubusercontent.com/tmux/tmux/master/terminfo/t/tmux-256color \
      | tic -x -o "$HOME/.terminfo" - || true
  fi
  say "Installing Maple Mono NF font..."
  FONT_URL="$(curl -fsSL https://api.github.com/repos/subframe7536/maple-font/releases/latest 2>/dev/null | grep -oE 'https://[^"]*MapleMono-NF\.zip' | head -1 || true)"
  if [ -n "${FONT_URL:-}" ]; then
    tmp="$(mktemp -d)"
    curl -fsSL "$FONT_URL" -o "$tmp/MapleMono-NF.zip"
    mkdir -p "$HOME/Library/Fonts"
    unzip -oq "$tmp/MapleMono-NF.zip" -d "$HOME/Library/Fonts/"
    xattr -cr "$HOME"/Library/Fonts/MapleMono-NF*.ttf 2>/dev/null || true
    rm -rf "$tmp"
  else
    say "WARN: install Maple Mono NF manually from"
    say "https://github.com/subframe7536/maple-font/releases into ~/Library/Fonts"
  fi
fi

say "Writing config files..."

write_file $HOME/.config/kitty/kitty.conf <<'MANUAL_EOF'
# ~/.config/kitty/kitty.conf  (macOS-adapted)
# Theme colors baked in from the Omarchy "terminus" theme (originally an
# `include ~/.local/state/omarchy/current/theme/kitty.conf`, which does not
# exist on macOS). Re-theme by editing theme.conf.
include ~/.config/kitty/theme.conf

# Font
font_family Maple Mono NF
bold_italic_font auto
font_size        12.5

# Window
window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0
background_opacity 0.70
background_blur 1

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
# Send Shift+Enter as CSI-u so TUIs can distinguish it from Enter.
map shift+enter send_text all \e[13;2u
# Kitty legacy encoding sends Alt+Shift+Enter the same as Alt+Enter; send CSI-u so tmux can match M-S-Enter.
map alt+shift+enter send_text all \e[13;4u

# macOS: make Option act as Alt/Meta so the tmux M-* bindings work
# (M-Enter split, M-Escape kill-pane, M-Left/M-Right windows, ...).
# Use `left` instead of `yes` if you want the left Option key to keep typing
# special characters.
macos_option_as_alt yes

# Allow remote access
# allow_remote_control yes

# Aesthetics
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor
enable_audio_bell no

# Smooth Cursor
cursor_trail 4
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Match monitor refresh rate
repaint_delay 10
sync_to_monitor yes
input_delay 0
wheel_scroll_multiplier 3.0

# The original config pointed kitty's remote-control socket at
# ${XDG_RUNTIME_DIR}/omarchy-kitty-{kitty_pid} for Omarchy/Hyprland cwd lookup.
# macOS has no XDG_RUNTIME_DIR and no Hyprland, so it is disabled by default.
# If you need the remote-control socket, uncomment (keep the path < ~104 chars):
# listen_on unix:/tmp/kitty-{kitty_pid}
MANUAL_EOF

write_file $HOME/.config/kitty/theme.conf <<'MANUAL_EOF'
foreground #d8cbb4
background #0c1626
selection_foreground #f2e8d5
selection_background #26364e

cursor #f2e8d5
cursor_text_color #0c1626

active_border_color #d9a862
active_tab_background #d9a862

color0 #0c1626
color1 #db684c
color2 #93b56f
color3 #d9a862
color4 #6e93bb
color5 #ab7fa8
color6 #7fa8ab
color7 #d8cbb4
color8 #5e6e87
color9 #e07a5f
color10 #a8c48a
color11 #f0d4a0
color12 #8fb0d4
color13 #c9a3c4
color14 #a8ccce
color15 #f2e8d5
MANUAL_EOF

write_file $HOME/.config/tmux/tmux.conf <<'MANUAL_EOF'
# Prefix
set -g prefix C-Space
set -g prefix2 C-b
bind C-Space send-prefix

# Reload config
bind q source-file ~/.config/tmux/tmux.conf \; display "Configuration reloaded"

# Vi mode for copy
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Pane Controls
bind -n M-Enter split-window -v -c "#{pane_current_path}"
bind -n M-S-Enter split-window -h -c "#{pane_current_path}"
bind -n M-Escape kill-pane

bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind x kill-pane

bind -n C-M-Left select-pane -L
bind -n C-M-Right select-pane -R
bind -n C-M-Up select-pane -U
bind -n C-M-Down select-pane -D

bind -n C-M-S-Left resize-pane -L 5
bind -n C-M-S-Down resize-pane -D 5
bind -n C-M-S-Up resize-pane -U 5
bind -n C-M-S-Right resize-pane -R 5

# Window navigation
bind r command-prompt -I "#W" "rename-window -- '%%'"
bind c new-window -c "#{pane_current_path}"
bind k kill-window

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-Left select-window -t -1
bind -n M-Right select-window -t +1
bind -n M-S-Left swap-window -t -1 \; select-window -t -1
bind -n M-S-Right swap-window -t +1 \; select-window -t +1

# Session controls
bind R command-prompt -I "#S" "rename-session -- '%%'"
bind C new-session -c "#{pane_current_path}"
bind K kill-session
bind P switch-client -p
bind N switch-client -n

bind -n M-Up switch-client -p
bind -n M-Down switch-client -n

# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g escape-time 0
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
setw -g aggressive-resize on
set -g detach-on-destroy off
set -g extended-keys on
set -g extended-keys-format csi-u
set -ag terminal-features "xterm-kitty:extkeys"
set -sg escape-time 10

# Plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.config/tmux/plugins/vim-tmux-navigator/vim-tmux-navigator.tmux'

# Status bar
set -g status-position top
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""
set -gw automatic-rename on
set -gw automatic-rename-format '#{b:pane_current_path}'
set -g set-titles on
set -g set-titles-string '#h:#W'

# Theme
set -g status-style "bg=default,fg=default"
set -g status-left "#[fg=black,bg=blue,bold] #S #[bg=default] "
set -g status-right "#[fg=blue]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=brightblack]#h "
set -g window-status-format "#[fg=brightblack] #I:#W "
set -g window-status-current-format "#[fg=blue,bold] #I:#W "
set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=blue"
set -g message-style "bg=default,fg=blue"
set -g message-command-style "bg=default,fg=blue"
set -g mode-style "bg=blue,fg=black"
setw -g clock-mode-colour blue

# Enable OSC 52 clipboard forwarding for remote Neovim yanks.
set -as terminal-features ",*:clipboard"
MANUAL_EOF

write_file $HOME/.config/starship.toml <<'MANUAL_EOF'
add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$python$character"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
MANUAL_EOF

write_file $HOME/.config/tmuxinator/myproject.yml <<'MANUAL_EOF'
name: myproject
root: ~/Projects/myproject

windows:
  - nvim: nvim
  - agents:
      layout: main-vertical
      panes:
        - agent1: opencode
        - agent2: opencode
        - worker: opencode-slim
      focused_pane: agent1
MANUAL_EOF

write_file $HOME/.bashrc <<'MANUAL_EOF'
# ~/.bashrc  (macOS-adapted: Omarchy /etc/omarchy.conf sourcing removed)
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# MacPorts. Intel macOS uses the /opt/local prefix; no shellenv step needed.
if [ -d /opt/local/bin ]; then
  export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
fi

# Toolchain paths (mirrors the Linux machine)
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
# Ruby user gems. Adjust the ruby version dir if the macOS ruby differs
# (check with: gem env gemdir).
export PATH="$HOME/.local/share/gem/ruby/3.4.0/bin:$PATH"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

alias mux='tmuxinator'

# Adds ~/.local/bin to PATH (original line: . "$HOME/.local/share/../bin/env")
[ -f "$HOME/.local/bin/env" ] && . "$HOME/.local/bin/env"

# Prompt
command -v starship >/dev/null 2>&1 && eval "$(starship init bash)"

# --- Secrets: macOS Keychain first, then ~/.secrets/<service> ---------------
# Create Keychain items with the commands in SECRETS.md.
keychain_read() {
  local service="$1" val=""
  val="$(/usr/bin/security find-generic-password -a "${USER:?}" -s "$service" -w 2>/dev/null)" || true
  if [ -n "$val" ]; then
    printf '%s' "$val"
    return 0
  fi
  if [ -f "$HOME/.secrets/$service" ]; then
    tr -d '\n' < "$HOME/.secrets/$service"
    return 0
  fi
  return 1
}

if _or_key="$(keychain_read openrouter-key)"; then
  export OPENROUTER_API_KEY="$_or_key"
  unset _or_key
fi
if _c7_key="$(keychain_read context7-key)"; then
  export CONTEXT7_API_KEY="$_c7_key"
  unset _c7_key
fi

export PIG_HOME="$HOME/.config/pig"
MANUAL_EOF

write_file $HOME/.zshrc <<'MANUAL_EOF'
# ~/.zshrc  (macOS default shell)

# MacPorts. Intel macOS uses the /opt/local prefix; no shellenv step needed.
if [ -d /opt/local/bin ]; then
  export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
fi

# Toolchain paths (mirrors the Linux machine)
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
# Ruby user gems. Adjust the ruby version dir if the macOS ruby differs
# (check with: gem env gemdir).
export PATH="$HOME/.local/share/gem/ruby/3.4.0/bin:$PATH"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

alias mux='tmuxinator'

# Adds ~/.local/bin to PATH
[ -f "$HOME/.local/bin/env" ] && . "$HOME/.local/bin/env"

# Prompt
command -v starship >/dev/null 2>&1 && eval "$(starship init zsh)"

# --- Secrets: macOS Keychain first, then ~/.secrets/<service> ---------------
# Create Keychain items with the commands in SECRETS.md.
keychain_read() {
  local service="$1" val=""
  val="$(/usr/bin/security find-generic-password -a "${USER:?}" -s "$service" -w 2>/dev/null)" || true
  if [ -n "$val" ]; then
    printf '%s' "$val"
    return 0
  fi
  if [ -f "$HOME/.secrets/$service" ]; then
    tr -d '\n' < "$HOME/.secrets/$service"
    return 0
  fi
  return 1
}

if _or_key="$(keychain_read openrouter-key)"; then
  export OPENROUTER_API_KEY="$_or_key"
  unset _or_key
fi
if _c7_key="$(keychain_read context7-key)"; then
  export CONTEXT7_API_KEY="$_c7_key"
  unset _c7_key
fi

export PIG_HOME="$HOME/.config/pig"
MANUAL_EOF

write_file $HOME/.bash_profile <<'MANUAL_EOF'
# ~/.bash_profile  (macOS bash login shell loads this, then ~/.bashrc)
[[ -f ~/.bashrc ]] && . ~/.bashrc
MANUAL_EOF

write_file $HOME/.local/bin/env <<'MANUAL_EOF'
#!/bin/sh
# add binaries to PATH if they aren't added yet
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"$HOME/.local/share/../bin":*)
        ;;
    *)
        # Prepending path in case a system-installed binary needs to be overridden
        export PATH="$HOME/.local/share/../bin:$PATH"
        ;;
esac
MANUAL_EOF

write_file $HOME/.config/nvim/init.lua <<'MANUAL_EOF'
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
MANUAL_EOF

write_file $HOME/.config/nvim/lazyvim.json <<'MANUAL_EOF'
{
  "extras": [
    "lazyvim.plugins.extras.ai.copilot-native",
    "lazyvim.plugins.extras.editor.neo-tree",
    "lazyvim.plugins.extras.lang.docker",
    "lazyvim.plugins.extras.lang.go",
    "lazyvim.plugins.extras.lang.java",
    "lazyvim.plugins.extras.lang.json",
    "lazyvim.plugins.extras.lang.markdown",
    "lazyvim.plugins.extras.lang.prisma",
    "lazyvim.plugins.extras.lang.sql",
    "lazyvim.plugins.extras.lang.tailwind",
    "lazyvim.plugins.extras.lang.toml",
    "lazyvim.plugins.extras.lang.typescript.biome",
    "lazyvim.plugins.extras.lang.typescript.oxc",
    "lazyvim.plugins.extras.linting.eslint",
    "lazyvim.plugins.extras.util.mini-hipatterns"
  ],
  "install_version": 8,
  "news": {
    "NEWS.md": "10960"
  },
  "version": 8
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/config/autocmds.lua <<'MANUAL_EOF'
-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
MANUAL_EOF

write_file $HOME/.config/nvim/lua/config/keymaps.lua <<'MANUAL_EOF'
-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
MANUAL_EOF

write_file $HOME/.config/nvim/lua/config/lazy.lua <<'MANUAL_EOF'
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import/override with your plugins
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.python" },
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = {
    enabled = true, -- check for plugin updates periodically
    notify = false, -- notify on update
  }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
MANUAL_EOF

write_file $HOME/.config/nvim/lua/config/options.lua <<'MANUAL_EOF'
require("config.remote_clipboard").setup()
-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here

vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true

vim.g.autoformat = true
MANUAL_EOF

write_file $HOME/.config/nvim/lua/config/remote_clipboard.lua <<'MANUAL_EOF'
-- Cross-platform remote clipboard for yanks that must reach another machine.
--
-- Every copy is also emitted as OSC 52 (inside tmux this becomes a tmux buffer,
-- rebroadcast to every attached client, local or SSH). Paste prefers a native
-- clipboard when one is available (macOS pbcopy/pbpaste, Linux/Wayland
-- wl-copy/wl-paste); otherwise it falls back to an OSC 52 query that tmux (or
-- the terminal) answers.
--
-- Platform notes:
--   * macOS: uses pbcopy/pbpaste. /proc is unavailable, so the Linux-only
--     ancestor-process probe is skipped.
--   * Linux/Wayland: uses wl-copy/wl-paste when a display is present.
local M = {}

local has_mac = vim.fn.has("mac") == 1
local has_linux = vim.fn.has("linux") == 1

-- Linux-only: walk the process ancestry looking for a process name.
local function proc_lines(pid, file)
  local ok, lines = pcall(vim.fn.readfile, "/proc/" .. pid .. "/" .. file)
  return ok and lines or {}
end

local function proc_ppid(pid)
  for _, line in ipairs(proc_lines(pid, "status")) do
    local ppid = line:match("^PPid:%s+(%d+)")
    if ppid then
      return tonumber(ppid)
    end
  end
end

local function ancestor_process_named(name)
  if not has_linux then
    return false
  end

  local pid = vim.fn.getpid()

  for _ = 1, 16 do
    local ppid = proc_ppid(pid)
    if not ppid or ppid <= 1 then
      return false
    end

    local comm = proc_lines(ppid, "comm")[1] or ""
    if comm:find(name, 1, true) then
      return true
    end

    pid = ppid
  end

  return false
end

-- Native (non-OSC52) clipboard commands for this platform, or nil.
local function native_clipboard()
  if has_mac then
    return {
      copy = { ["+"] = { "pbcopy" }, ["*"] = { "pbcopy" } },
      paste = { ["+"] = { "pbpaste" }, ["*"] = { "pbpaste" } },
    }
  end

  local has_wayland = vim.env.WAYLAND_DISPLAY ~= nil
    and vim.fn.executable("wl-copy") == 1
    and vim.fn.executable("wl-paste") == 1

  if has_wayland then
    return {
      copy = {
        ["+"] = { "wl-copy", "--sensitive", "--type", "text/plain" },
        ["*"] = { "wl-copy", "--sensitive", "--type", "text/plain", "--primary" },
      },
      paste = {
        ["+"] = { "wl-paste", "--no-newline" },
        ["*"] = { "wl-paste", "--no-newline", "--primary" },
      },
    }
  end

  return nil
end

local function osc52_enabled()
  return vim.g.remote_clipboard_osc52 ~= false
    and vim.g.omarchy_remote_clipboard_osc52 ~= false
end

function M.setup()
  local in_tmux = vim.env.TMUX ~= nil
  local in_ssh = vim.env.SSH_TTY ~= nil or vim.env.SSH_CONNECTION ~= nil
  local in_herdr = vim.env.HERDR_PANE_ID ~= nil or ancestor_process_named("herdr")

  if not (in_tmux or in_ssh or in_herdr) then
    return
  end

  local osc52 = require("vim.ui.clipboard.osc52")
  local native = native_clipboard()

  local function copy(register)
    local emit = osc52.copy(register)

    return function(lines)
      if native then
        vim.fn.system(native.copy[register], lines)
      end

      if osc52_enabled() then
        emit(lines)
      end
    end
  end

  local function paste(register)
    if not native then
      return osc52.paste(register)
    end

    return function()
      local lines = vim.fn.systemlist(native.paste[register], "", 1)
      return vim.v.shell_error == 0 and lines or {}
    end
  end

  vim.g.clipboard = {
    name = "RemoteClipboard",
    copy = { ["+"] = copy("+"), ["*"] = copy("*") },
    paste = { ["+"] = paste("+"), ["*"] = paste("*") },
    cache_enabled = 0,
  }
end

return M
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/all-themes.lua <<'MANUAL_EOF'
return {
	-- Load all theme plugins but don't apply them
	-- This ensures all colorschemes are available for hot-reloading
	{
		"ribru17/bamboo.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"bjarneo/aether.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"bjarneo/ethereal.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"bjarneo/hackerman.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"bjarneo/vantablack.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"bjarneo/white.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"catppuccin/nvim",
		name = "catppuccin",
		lazy = true,
		priority = 1000,
	},
	{
		"sainnhe/everforest",
		lazy = true,
		priority = 1000,
	},
	{
		"kepano/flexoki-neovim",
		lazy = true,
		priority = 1000,
	},
	{
		"ellisonleao/gruvbox.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"rebelot/kanagawa.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"tahayvr/matteblack.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"loctvl842/monokai-pro.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"shaunsingh/nord.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"rose-pine/neovim",
		name = "rose-pine",
		lazy = true,
		priority = 1000,
	},
	{
		"folke/tokyonight.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"OldJobobo/miasma.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"OldJobobo/retro-82.nvim",
		lazy = true,
		priority = 1000,
	},
	{
		"omacom-io/lumon.nvim",
		lazy = true,
		priority = 1000,
	},
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/cssls.lua <<'MANUAL_EOF'
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        cssls = {},
      },
    },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/disabled.lua <<'MANUAL_EOF'
return {}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/disable-news-alert.lua <<'MANUAL_EOF'
return {
	"LazyVim/LazyVim",
	opts = {
		news = {
			lazyvim = false,
			neovim = false,
		},
	},
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/example.lua <<'MANUAL_EOF'
-- since this is just an example spec, don't actually load anything here and return an empty spec
-- stylua: ignore
if true then return {} end

-- every spec file under the "plugins" directory will be loaded automatically by lazy.nvim
--
-- In your plugin files, you can:
-- * add extra plugins
-- * disable/enabled LazyVim plugins
-- * override the configuration of LazyVim plugins
return {
  -- add gruvbox
  { "ellisonleao/gruvbox.nvim" },

  -- Configure LazyVim to load gruvbox
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "gruvbox",
    },
  },

  -- change trouble config
  {
    "folke/trouble.nvim",
    -- opts will be merged with the parent spec
    opts = { use_diagnostic_signs = true },
  },

  -- disable trouble
  { "folke/trouble.nvim", enabled = false },

  -- override nvim-cmp and add cmp-emoji
  {
    "hrsh7th/nvim-cmp",
    dependencies = { "hrsh7th/cmp-emoji" },
    ---@param opts cmp.ConfigSchema
    opts = function(_, opts)
      table.insert(opts.sources, { name = "emoji" })
    end,
  },

  -- change some telescope options and a keymap to browse plugin files
  {
    "nvim-telescope/telescope.nvim",
    keys = {
      -- add a keymap to browse plugin files
      -- stylua: ignore
      {
        "<leader>fp",
        function() require("telescope.builtin").find_files({ cwd = require("lazy.core.config").options.root }) end,
        desc = "Find Plugin File",
      },
    },
    -- change some options
    opts = {
      defaults = {
        layout_strategy = "horizontal",
        layout_config = { prompt_position = "top" },
        sorting_strategy = "ascending",
        winblend = 0,
      },
    },
  },

  -- add pyright to lspconfig
  {
    "neovim/nvim-lspconfig",
    ---@class PluginLspOpts
    opts = {
      ---@type lspconfig.options
      servers = {
        -- pyright will be automatically installed with mason and loaded with lspconfig
        pyright = {},
      },
    },
  },

  -- add tsserver and setup with typescript.nvim instead of lspconfig
  {
    "neovim/nvim-lspconfig",
    dependencies = {
      "jose-elias-alvarez/typescript.nvim",
      init = function()
        require("lazyvim.util").lsp.on_attach(function(_, buffer)
          -- stylua: ignore
          vim.keymap.set( "n", "<leader>co", "TypescriptOrganizeImports", { buffer = buffer, desc = "Organize Imports" })
          vim.keymap.set("n", "<leader>cR", "TypescriptRenameFile", { desc = "Rename File", buffer = buffer })
        end)
      end,
    },
    ---@class PluginLspOpts
    opts = {
      ---@type lspconfig.options
      servers = {
        -- tsserver will be automatically installed with mason and loaded with lspconfig
        tsserver = {},
      },
      -- you can do any additional lsp server setup here
      -- return true if you don't want this server to be setup with lspconfig
      ---@type table<string, fun(server:string, opts:_.lspconfig.options):boolean?>
      setup = {
        -- example to setup with typescript.nvim
        tsserver = function(_, opts)
          require("typescript").setup({ server = opts })
          return true
        end,
        -- Specify * to use this function as a fallback for any server
        -- ["*"] = function(server, opts) end,
      },
    },
  },

  -- for typescript, LazyVim also includes extra specs to properly setup lspconfig,
  -- treesitter, mason and typescript.nvim. So instead of the above, you can use:
  { import = "lazyvim.plugins.extras.lang.typescript" },

  -- add more treesitter parsers
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "yaml",
      },
    },
  },

  -- since `vim.tbl_deep_extend`, can only merge tables and not lists, the code above
  -- would overwrite `ensure_installed` with the new value.
  -- If you'd rather extend the default config, use the code below instead:
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      -- add tsx and treesitter
      vim.list_extend(opts.ensure_installed, {
        "tsx",
        "typescript",
      })
    end,
  },

  -- the opts function can also be used to change the default opts:
  {
    "nvim-lualine/lualine.nvim",
    event = "VeryLazy",
    opts = function(_, opts)
      table.insert(opts.sections.lualine_x, {
        function()
          return "😄"
        end,
      })
    end,
  },

  -- or you can return new options to override all the defaults
  {
    "nvim-lualine/lualine.nvim",
    event = "VeryLazy",
    opts = function()
      return {
        --[[add your custom lualine config here]]
      }
    end,
  },

  -- use mini.starter instead of alpha
  { import = "lazyvim.plugins.extras.ui.mini-starter" },

  -- add jsonls and schemastore packages, and setup treesitter for json, json5 and jsonc
  { import = "lazyvim.plugins.extras.lang.json" },

  -- add any tools you want to have installed below
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "stylua",
        "shellcheck",
        "shfmt",
        "flake8",
      },
    },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/file-browser.lua <<'MANUAL_EOF'
return {
  "nvim-telescope/telescope-file-browser.nvim",
  keys = {
    {
      "<leader>s0",
      ":Telescope file_browser path=%:p:h=%:p:h<cr>",
      desc = "Browser Files",
    },
  },
  opts = {
    hidden = true,
  },
  config = function(_, opts)
    require("telescope").setup({ extensions = { file_browser = opts } })
    require("telescope").load_extension("file_browser")
  end,
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/go-lint.lua <<'MANUAL_EOF'
return {
  {
    "mfussenegger/nvim-lint",
    opts = function(_, opts)
      local root = vim.fs.root(0, { "go.mod" })
      if root then
        opts.linters = opts.linters or {}
        opts.linters.golangcilint = {
          append_fname = false,
          cwd = root,
          cmd = "golangci-lint",
          args = {
            "run",
            "--output.json.path=stdout",
            "--output.text.path=",
            "--output.tab.path=",
            "--output.html.path=",
            "--output.checkstyle.path=",
            "--output.code-climate.path=",
            "--output.junit-xml.path=",
            "--output.teamcity.path=",
            "--output.sarif.path=",
            "--issues-exit-code=0",
            "--show-stats=false",
            "--path-mode=abs",
          },
        }
      end
    end,
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/harpoon.lua <<'MANUAL_EOF'
return {
  "ThePrimeagen/harpoon",
  branch = "harpoon2",
  dependencies = { "nvim-lua/plenary.nvim" },

  config = function()
    local harpoon = require("harpoon")
    harpoon:setup({})
  end,
  keys = {
    {
      "<leader>ha",
      function()
        require("harpoon"):list():add()
      end,
      desc = "Harpoon Add File",
    },
    {
      "<leader>hh",
      function()
        local harpoon = require("harpoon")
        harpoon.ui:toggle_quick_menu(harpoon:list())
      end,
      desc = "Harpoon Menu",
    },
    {
      "<leader>hd",
      function()
        require("harpoon"):list():remove()
      end,
      desc = "Harpoon Remove File",
    },
    {
      "<leader>1",
      function()
        require("harpoon"):list():select(1)
      end,
      desc = "Harpoon File 1",
    },
    {
      "<leader>2",
      function()
        require("harpoon"):list():select(2)
      end,
      desc = "Harpoon File 2",
    },
    {
      "<leader>3",
      function()
        require("harpoon"):list():select(3)
      end,
      desc = "Harpoon File 3",
    },
    {
      "<leader>4",
      function()
        require("harpoon"):list():select(4)
      end,
      desc = "Harpoon File 4",
    },
    {
      "<C-S-P>",
      function()
        require("harpoon"):list():prev()
      end,
      desc = "Harpoon Previous",
    },
    {
      "<C-S-N>",
      function()
        require("harpoon"):list():next()
      end,
      desc = "Harpoon Next",
    },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/import.lua <<'MANUAL_EOF'
return {
  "piersolenski/telescope-import.nvim",
  dependencies = { "nvim-telescope/telescope.nvim" },
  config = function()
    require("telescope").load_extension("import")
  end,
  keys = {
    -- Map a key to trigger the import picker
    { "<leader>ci", "<cmd>Telescope import<cr>", desc = "Import" },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/neoclip.lua <<'MANUAL_EOF'
return {
  "AckslD/nvim-neoclip.lua",
  dependencies = {
    { "nvim-telescope/telescope.nvim" },
    { "nvim-telescope/telescope-ui-select.nvim" },
  },
  config = function()
    require("neoclip").setup()
    require("telescope").load_extension("neoclip")
  end,
  keys = {
    {
      "<leader>p",
      function()
        local neoclip = require("telescope").extensions.neoclip
        local actions = require("telescope.actions")
        local state = require("telescope.actions.state")
        local action_set = require("telescope.actions.set")
        neoclip.default({
          attach_mappings = function(_, map)
            map("i", "<CR>", function(prompt_bufnr)
              local selection = state.get_selected_entry()
              if selection then
                local content = selection.value
                vim.fn.setreg('"', content)
                vim.api.nvim_put({ content }, "c", true, true)
              end
              actions.close(prompt_bufnr)
            end)
            map("n", "<CR>", function(prompt_bufnr)
              local selection = state.get_selected_entry()
              if selection then
                local content = selection.value
                vim.fn.setreg('"', content)
                vim.api.nvim_put({ content }, "c", true, true)
              end
              actions.close(prompt_bufnr)
            end)
            return true
          end,
        })
      end,
      desc = "Clipboard history",
    },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/neo-tree.lua <<'MANUAL_EOF'
return {
  "nvim-neo-tree/neo-tree.nvim",
  opts = {
    filesystem = {
      filtered_items = {
        visible = true,
        hide_dotfiles = false,
        hide_gitignored = false,
      },
    },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/nvim-lint.lua <<'MANUAL_EOF'
local HOME = os.getenv("HOME")
return {
  "mfussenegger/nvim-lint",
  optional = true,
  opts = {
    linters = {
      ["markdownlint-cli2"] = {
        args = { "--config", HOME .. "/.markdownlint-cli2.yaml", "--" },
      },
    },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/nvim-tmux-navigator.lua <<'MANUAL_EOF'
return {
  "christoomey/vim-tmux-navigator",
  cmd = {
    "TmuxNavigateLeft",
    "TmuxNavigateDown",
    "TmuxNavigateUp",
    "TmuxNavigateRight",
    "TmuxNavigatePrevious",
    "TmuxNavigatorProcessList",
  },
  keys = {
    { "<c-h>", "<cmd><C-U>TmuxNavigateLeft<cr>" },
    { "<c-j>", "<cmd><C-U>TmuxNavigateDown<cr>" },
    { "<c-k>", "<cmd><C-U>TmuxNavigateUp<cr>" },
    { "<c-l>", "<cmd><C-U>TmuxNavigateRight<cr>" },
    { "<c-\\>", "<cmd><C-U>TmuxNavigatePrevious<cr>" },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/nvim-ufo.lua <<'MANUAL_EOF'
return {
  {
    "kevinhwang91/nvim-ufo",
    dependencies = { "kevinhwang91/promise-async" },
    event = "BufReadPost",
    init = function()
      -- Recommended global options for nvim-ufo
      vim.o.foldcolumn = "1"
      vim.o.foldlevel = 99
      vim.o.foldlevelstart = 99
      vim.o.foldenable = true
    end,
    config = function()
      -- Keymaps to open/close all folds
      vim.keymap.set("n", "zR", require("ufo").openAllFolds)
      vim.keymap.set("n", "zM", require("ufo").closeAllFoldz or require("ufo").closeAllFolds)

      require("ufo").setup({
        provider_selector = function(bufnr, filetype, buftype)
          return { "lsp", "indent" }
        end,
      })
    end,
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/omarchy-theme-hotreload.lua <<'MANUAL_EOF'
return {
	{
		name = "theme-hotreload",
		dir = vim.fn.stdpath("config"),
		lazy = false,
		priority = 1000,
		config = function()
			local transparency_file = vim.fn.stdpath("config") .. "/plugin/after/transparency.lua"

			vim.api.nvim_create_autocmd("User", {
				pattern = "LazyReload",
				callback = function()
					-- Unload the theme module
					package.loaded["plugins.theme"] = nil

					vim.schedule(function()
						local ok, theme_spec = pcall(require, "plugins.theme")
						if not ok then
							return
						end

						-- Find the theme plugin and unload it
						local theme_plugin_name = nil
						for _, spec in ipairs(theme_spec) do
							if spec[1] and spec[1] ~= "LazyVim/LazyVim" then
								theme_plugin_name = spec.name or spec[1]
								break
							end
						end

						-- Clear all highlight groups before applying new theme
						vim.cmd("highlight clear")
						if vim.fn.exists("syntax_on") then
							vim.cmd("syntax reset")
						end

						-- Reset background to default so colorscheme can set it properly (light themes will set to light)
						vim.o.background = "dark"

						-- Unload theme plugin modules to force full reload
						if theme_plugin_name then
							local plugin = require("lazy.core.config").plugins[theme_plugin_name]
							if plugin then
								-- Unload all lua modules from the plugin directory
								local plugin_dir = plugin.dir .. "/lua"
								require("lazy.core.util").walkmods(plugin_dir, function(modname)
									package.loaded[modname] = nil
									package.preload[modname] = nil
								end)
							end
						end

						-- Find and apply the new colorscheme
						for _, spec in ipairs(theme_spec) do
							if spec[1] == "LazyVim/LazyVim" and spec.opts and spec.opts.colorscheme then
								local colorscheme = spec.opts.colorscheme

								-- Load the colorscheme plugin
								require("lazy.core.loader").colorscheme(colorscheme)

								vim.defer_fn(function()
									-- Apply the colorscheme (it will set background itself)
									pcall(vim.cmd.colorscheme, colorscheme)

									-- Force redraw to update all UI elements
									vim.cmd("redraw!")

									-- Reload transparency settings
									if vim.fn.filereadable(transparency_file) == 1 then
										vim.defer_fn(function()
											vim.cmd.source(transparency_file)

											-- Trigger UI updates for various plugins
											vim.api.nvim_exec_autocmds("ColorScheme", { modeline = false })
											vim.api.nvim_exec_autocmds("VimEnter", { modeline = false })

											-- Final redraw
											vim.cmd("redraw!")
										end, 5)
									end
								end, 5)

								break
							end
						end
					end)
				end,
			})
		end,
	},
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/rescript.lua <<'MANUAL_EOF'
return { "rescript-lang/vim-rescript", tag = "v3.0.0" }
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/snacks-animated-scrolling-off.lua <<'MANUAL_EOF'
return {
	"folke/snacks.nvim",
	opts = {
		scroll = {
			enabled = false, -- Disable scrolling animations
		},
	},
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/snacks.lua <<'MANUAL_EOF'
return {
  {
    "folke/snacks.nvim",
    opts = {
      picker = {
        grep = {
          exclude = { "node_modules", ".opencode" },
        },
      },
    },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/snacks-nvim.lua <<'MANUAL_EOF'
return {
  "folke/snacks.nvim",
  opts = {
    picker = {
      hidden = true,
      ignored = true,
      sources = {
        files = { hidden = true },
      },
    },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/telescope.lua <<'MANUAL_EOF'
return {
  {
    "nvim-telescope/telescope.nvim",
    opts = {
      defaults = {
        file_ignore_patterns = {
          "node_modules/.*",
          ".opencode/.*",
        },
      },
    },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/theme.lua <<'MANUAL_EOF'
return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#0c1626",
        dark_bg = "#09111e",
        darker_bg = "#070c15",
        lighter_bg = "#17243a",

        fg = "#d8cbb4",
        dark_fg = "#9f9f9e",
        light_fg = "#e5dac5",
        bright_fg = "#f2e8d5",
        muted = "#5e6e87",

        red = "#db684c",
        yellow = "#d9a862",
        orange = "#dd8b57",
        green = "#93b56f",
        cyan = "#7fa8ab",
        blue = "#6e93bb",
        magenta = "#ab7fa8",
        brown = "#7a5e37",

        bright_red = "#e07a5f",
        bright_yellow = "#f0d4a0",
        bright_green = "#a8c48a",
        bright_cyan = "#a8ccce",
        bright_blue = "#8fb0d4",
        bright_magenta = "#c9a3c4",

        accent = "#d9a862",
        cursor = "#f2e8d5",
        foreground = "#d8cbb4",
        background = "#0c1626",
        selection = "#26364e",
        selection_foreground = "#f2e8d5",
        selection_background = "#26364e",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/undotree.lua <<'MANUAL_EOF'
return {
  "mbbill/undotree",
  cmd = "UndotreeToggle",
  keys = {
    {
      "<leader>U",
      function()
        vim.cmd.UndotreeToggle()
      end,
      desc = "Toggle undotree",
    },
  },
}
MANUAL_EOF

write_file $HOME/.config/nvim/lua/plugins/vim-glsl.lua <<'MANUAL_EOF'
return {
  { "tikhomirov/vim-glsl" },
}
MANUAL_EOF

write_file $HOME/.config/nvim/.neoconf.json <<'MANUAL_EOF'
{
  "neodev": {
    "library": {
      "enabled": true,
      "plugins": true
    }
  },
  "neoconf": {
    "plugins": {
      "lua_ls": {
        "enabled": true
      }
    }
  }
}
MANUAL_EOF

write_file $HOME/.config/nvim/plugin/after/transparency.lua <<'MANUAL_EOF'
-- Make highlight groups transparent while preserving their other attributes
local function make_transparent(name)
	local ok, hl = pcall(vim.api.nvim_get_hl, 0, { name = name, link = false })
	if ok then
		hl.bg = nil
		vim.api.nvim_set_hl(0, name, hl)
	end
end

local groups = {
	-- transparent background
	"Normal",
	"NormalFloat",
	"FloatBorder",
	"Pmenu",
	"Terminal",
	"EndOfBuffer",
	"FoldColumn",
	"Folded",
	"SignColumn",
	"LineNr",
	"CursorLineNr",
	"NormalNC",
	"WhichKeyFloat",
	"TelescopeBorder",
	"TelescopeNormal",
	"TelescopePromptBorder",
	"TelescopePromptTitle",
	-- neotree
	"NeoTreeNormal",
	"NeoTreeNormalNC",
	"NeoTreeVertSplit",
	"NeoTreeWinSeparator",
	"NeoTreeEndOfBuffer",
	-- nvim-tree
	"NvimTreeNormal",
	"NvimTreeVertSplit",
	"NvimTreeEndOfBuffer",
	-- notify
	"NotifyINFOBody",
	"NotifyERRORBody",
	"NotifyWARNBody",
	"NotifyTRACEBody",
	"NotifyDEBUGBody",
	"NotifyINFOTitle",
	"NotifyERRORTitle",
	"NotifyWARNTitle",
	"NotifyTRACETitle",
	"NotifyDEBUGTitle",
	"NotifyINFOBorder",
	"NotifyERRORBorder",
	"NotifyWARNBorder",
	"NotifyTRACEBorder",
	"NotifyDEBUGBorder",
}

for _, name in ipairs(groups) do
	make_transparent(name)
end
MANUAL_EOF

write_file $HOME/.config/nvim/stylua.toml <<'MANUAL_EOF'
indent_type = "Spaces"
indent_width = 2
column_width = 120
MANUAL_EOF

say "Cloning tmux vim-tmux-navigator..."
mkdir -p "$HOME/.config/tmux/plugins"
if [ ! -d "$HOME/.config/tmux/plugins/vim-tmux-navigator" ]; then
  git clone --depth 1 \
    https://github.com/christoomey/vim-tmux-navigator \
    "$HOME/.config/tmux/plugins/vim-tmux-navigator" || true
fi

chmod 600 "$HOME/.secrets/"*-key 2>/dev/null || true

say "Done. Open a NEW terminal, then run: nvim"
