#!/usr/bin/env bash
# gen-manual.sh — generate a self-contained manual-install.sh from dotfiles/.
#
# Why: on a locked-down machine the repo cannot be cloned, so the configs must
# be entered by hand. This bundles every file into ONE script of `write_file`
# heredocs plus the MacPorts commands, so the whole env can be reproduced
# without any external repo access.
#
# Usage: tools/gen-manual.sh   (writes <repo>/manual-install.sh)
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOT="$REPO/dotfiles"
OUT="$REPO/manual-install.sh"

# Map a dotfiles-relative path to the literal destination expression that will
# appear in the generated script (so $HOME is expanded on the target machine).
dest_for() {
  local rel="$1"
  case "$rel" in
    kitty/kitty.conf)   echo '$HOME/.config/kitty/kitty.conf' ;;
    kitty/theme.conf)   echo '$HOME/.config/kitty/theme.conf' ;;
    tmux/tmux.conf)     echo '$HOME/.config/tmux/tmux.conf' ;;
    starship.toml)      echo '$HOME/.config/starship.toml' ;;
    tmuxinator/*.yml)   echo "\$HOME/.config/tmuxinator/${rel#tmuxinator/}" ;;
    shell/bashrc)       echo '$HOME/.bashrc' ;;
    shell/zshrc)        echo '$HOME/.zshrc' ;;
    shell/bash_profile) echo '$HOME/.bash_profile' ;;
    local/bin/env)      echo '$HOME/.local/bin/env' ;;
    nvim/*)             echo "\$HOME/.config/nvim/${rel#nvim/}" ;;
    *) return 1 ;;
  esac
}

emit_file() {
  local rel="$1" dest
  dest="$(dest_for "$rel")" || return 0
  printf "\nwrite_file %s <<'MANUAL_EOF'\n" "$dest"
  # awk '1' guarantees a trailing newline so the heredoc terminator starts on
  # its own line even for source files that lack a final newline.
  awk '1' "$DOT/$rel"
  printf 'MANUAL_EOF\n'
}

{
  cat <<'HEADER'
#!/usr/bin/env bash
# manual-install.sh — self-contained (no repo clone required).
# Generated by tools/gen-manual.sh from the mac-setup dotfiles.
#
#   INSTALL_PORTS=0 bash manual-install.sh   # only write config files
#   bash manual-install.sh                   # write configs + install ports
set -euo pipefail

INSTALL_PORTS="${INSTALL_PORTS:-1}"
say() { printf '==> %s\n' "$*"; }

write_file() {
  local dest="$1"
  mkdir -p "$(dirname "$dest")"
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    cp "$dest" "$dest.bak.$(date +%s)"
  fi
  cat > "$dest"
}

if [ "$INSTALL_PORTS" = "1" ]; then
  if ! xcode-select -p >/dev/null 2>&1; then
    say "Installing Xcode Command Line Tools (finish the dialog, then re-run)..."
    xcode-select --install || true
  fi
  if [ ! -x /opt/local/bin/port ]; then
    echo "MacPorts is not installed. Install the macOS 26 .pkg from"
    echo "https://www.macports.org/install.php and re-run this script."
    exit 1
  fi
  export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
  say "Updating MacPorts (sudo port selfupdate)..."
  sudo port selfupdate
  say "Installing ports..."
  sudo port install neovim ripgrep fd fzf lazygit tree-sitter-cli \
    nodejs22 python312 go tmux starship git kitty
  sudo port select --set python3 python312 || true
  sudo port select --set nodejs  nodejs22  || true
  if command -v infocmp >/dev/null 2>&1 && ! infocmp tmux-256color >/dev/null 2>&1; then
    say "Adding tmux-256color terminfo (fallback)..."
    curl -fsSL https://raw.githubusercontent.com/tmux/tmux/master/terminfo/t/tmux-256color \
      | tic -x -o "$HOME/.terminfo" - || true
  fi
  say "Installing Maple Mono NF font..."
  FONT_URL="$(curl -fsSL https://api.github.com/repos/subframe7536/maple-font/releases/latest 2>/dev/null | grep -oE 'https://[^"]*MapleMono-NF\.zip' | head -1 || true)"
  if [ -n "${FONT_URL:-}" ]; then
    tmp="$(mktemp -d)"
    curl -fsSL "$FONT_URL" -o "$tmp/MapleMono-NF.zip"
    mkdir -p "$HOME/Library/Fonts"
    unzip -oq "$tmp/MapleMono-NF.zip" -d "$HOME/Library/Fonts/"
    xattr -cr "$HOME"/Library/Fonts/MapleMono-NF*.ttf 2>/dev/null || true
    rm -rf "$tmp"
  else
    say "WARN: install Maple Mono NF manually from"
    say "https://github.com/subframe7536/maple-font/releases into ~/Library/Fonts"
  fi
fi

say "Writing config files..."
HEADER

  for rel in \
    kitty/kitty.conf kitty/theme.conf tmux/tmux.conf starship.toml \
    tmuxinator/myproject.yml shell/bashrc shell/zshrc shell/bash_profile local/bin/env
  do
    emit_file "$rel"
  done

  while IFS= read -r src; do
    rel="nvim/${src#"$DOT"/nvim/}"
    case "$rel" in
      nvim/lazy-lock.json|nvim/LICENSE|nvim/README.md|nvim/.gitignore) continue ;;
    esac
    emit_file "$rel"
  done < <(find "$DOT/nvim" -type f | sort)

  cat <<'FOOTER'

say "Cloning tmux vim-tmux-navigator..."
mkdir -p "$HOME/.config/tmux/plugins"
if [ ! -d "$HOME/.config/tmux/plugins/vim-tmux-navigator" ]; then
  git clone --depth 1 \
    https://github.com/christoomey/vim-tmux-navigator \
    "$HOME/.config/tmux/plugins/vim-tmux-navigator" || true
fi

chmod 600 "$HOME/.secrets/"*-key 2>/dev/null || true

say "Done. Open a NEW terminal, then run: nvim"
FOOTER
} > "$OUT"

chmod +x "$OUT"
printf 'wrote %s (%s lines, %s)\n' "$OUT" "$(wc -l < "$OUT")" "$(du -h "$OUT" | cut -f1)"
