#!/usr/bin/env bash
# gen-manual.sh — generate a self-contained manual-install.sh from dotfiles/.
#
# Why: on a locked-down machine the repo cannot be cloned, so the configs must
# be entered by hand. This bundles every file into ONE script of `write_file`
# heredocs plus the Homebrew commands, so the whole env can be reproduced
# without any external repo access.
#
# Usage: tools/gen-manual.sh   (writes <repo>/manual-install.sh)
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOT="$REPO/dotfiles"
OUT="$REPO/manual-install.sh"

# Map a dotfiles-relative path to the literal destination expression that will
# appear in the generated script (so $HOME is expanded on the target machine).
dest_for() {
  local rel="$1"
  case "$rel" in
    kitty/kitty.conf)   echo '$HOME/.config/kitty/kitty.conf' ;;
    kitty/theme.conf)   echo '$HOME/.config/kitty/theme.conf' ;;
    tmux/tmux.conf)     echo '$HOME/.config/tmux/tmux.conf' ;;
    starship.toml)      echo '$HOME/.config/starship.toml' ;;
    tmuxinator/*.yml)   echo "\$HOME/.config/tmuxinator/${rel#tmuxinator/}" ;;
    shell/bashrc)       echo '$HOME/.bashrc' ;;
    shell/zshrc)        echo '$HOME/.zshrc' ;;
    shell/bash_profile) echo '$HOME/.bash_profile' ;;
    local/bin/env)      echo '$HOME/.local/bin/env' ;;
    nvim/*)             echo "\$HOME/.config/nvim/${rel#nvim/}" ;;
    *) return 1 ;;
  esac
}

emit_file() {
  local rel="$1" dest
  dest="$(dest_for "$rel")" || return 0
  printf "\nwrite_file %s <<'MANUAL_EOF'\n" "$dest"
  # awk '1' guarantees a trailing newline so the heredoc terminator starts on
  # its own line even for source files that lack a final newline.
  awk '1' "$DOT/$rel"
  printf 'MANUAL_EOF\n'
}

{
  cat <<'HEADER'
#!/usr/bin/env bash
# manual-install.sh — self-contained (no repo clone required).
# Generated by tools/gen-manual.sh from the mac-setup dotfiles.
#
#   INSTALL_BREW=0 bash manual-install.sh   # only write config files
#   bash manual-install.sh                  # write configs + install brew packages
set -euo pipefail

INSTALL_BREW="${INSTALL_BREW:-1}"
say() { printf '==> %s\n' "$*"; }

write_file() {
  local dest="$1"
  mkdir -p "$(dirname "$dest")"
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    cp "$dest" "$dest.bak.$(date +%s)"
  fi
  cat > "$dest"
}

if [ "$INSTALL_BREW" = "1" ]; then
  if ! xcode-select -p >/dev/null 2>&1; then
    say "Installing Xcode Command Line Tools (finish the dialog, then re-run)..."
    xcode-select --install || true
  fi
  if ! command -v brew >/dev/null 2>&1; then
    say "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  eval "$(/opt/homebrew/bin/brew shellenv)"
  say "Installing formulae..."
  brew install neovim ripgrep fd fzf lazygit tree-sitter-cli \
    node python3 go tmux starship tmuxinator git
  say "Installing casks (kitty + Maple Mono NF)..."
  brew install --cask kitty font-maple-mono-nf
  if command -v infocmp >/dev/null 2>&1 && ! infocmp tmux-256color >/dev/null 2>&1; then
    say "Adding tmux-256color terminfo..."
    curl -fsSL https://raw.githubusercontent.com/tmux/tmux/master/terminfo/t/tmux-256color \
      | tic -x -o "$HOME/.terminfo" - || true
  fi
fi

say "Writing config files..."
HEADER

  for rel in \
    kitty/kitty.conf kitty/theme.conf tmux/tmux.conf starship.toml \
    tmuxinator/myproject.yml shell/bashrc shell/zshrc shell/bash_profile local/bin/env
  do
    emit_file "$rel"
  done

  while IFS= read -r src; do
    rel="nvim/${src#"$DOT"/nvim/}"
    case "$rel" in
      nvim/lazy-lock.json|nvim/LICENSE|nvim/README.md|nvim/.gitignore) continue ;;
    esac
    emit_file "$rel"
  done < <(find "$DOT/nvim" -type f | sort)

  cat <<'FOOTER'

say "Cloning tmux vim-tmux-navigator..."
mkdir -p "$HOME/.config/tmux/plugins"
if [ ! -d "$HOME/.config/tmux/plugins/vim-tmux-navigator" ]; then
  git clone --depth 1 \
    https://github.com/christoomey/vim-tmux-navigator \
    "$HOME/.config/tmux/plugins/vim-tmux-navigator" || true
fi

chmod 600 "$HOME/.secrets/"*-key 2>/dev/null || true

say "Done. Open a NEW terminal, then run: nvim"
FOOTER
} > "$OUT"

chmod +x "$OUT"
printf 'wrote %s (%s lines, %s)\n' "$OUT" "$(wc -l < "$OUT")" "$(du -h "$OUT" | cut -f1)"
